rename cmake project to "cunthook" and other things
Summary:

* Renamed cmake project to "cunthook"
* Removed need to use cmake to install data path
* Realizing that you don't need to install gdbbin everytime

diff --git a/update b/update
--- a/update
+++ b/update
@@ -10,26 +10,34 @@ if [ $(id -u) -eq 0 ]; then
     exit 1;
 fi
 
-#-- Build configuration folder for things like killsays or spam
-#-- but also for ipc server data and other things.
+#-- Removes the need for cmake or a seperate file to install the data to 
+#-- opt/cunthook and instead dynamically checks for requirement of sudo
+#-- making the update file actually 1 file.
 function InstallData() {
     [[ ! -z "$SUDO_USER" ]] && user=$SUDO_USER || user=$LOGNAME;
-    DATA_PATH=${1:-/opt/cathook/data};
+    DATA_PATH=${1:-/opt/cunthook/data};
+    MAIN_PATH=${1:-/opt/cunthook};
 
     if ! [ -d "$DATA_PATH" ]; then
         echo -e "The data path \"$DATA_PATH\" doesn't exists. Creating... \n";
-        mkdir -p "$DATA_PATH";
-        chown -R $user "$DATA_PATH";
-        chmod -R 774 "$DATA_PATH";
+        mkdir -p "$MAIN_PATH" || {
+            echo -e "Failed to created directory. using sudo...\n";
+            sudo mkdir -p "$MAIN_PATH";
+        };
+        mkdir -p "$DATA_PATH" || {
+            echo -e "Failed to create data path. using sudo...\n";
+            sudo mkdir -p "$DATA_PATH";
+        };
+
         echo "Created data path";
     fi
 
     echo -e "Checking data from \"Resources/config\" to \"$DATA_PATH\" \n";
 
-    rsync -avh "Project/data/" "$DATA_PATH";
-    rsync -avh --ignore-existing "Resources/config/" "$DATA_PATH";
-    chown -R $user "$DATA_PATH";
-    chmod -R 774 "$DATA_PATH";
+    rsync -avh "Project/data/" "$DATA_PATH" || { sudo rsync -avh "Project/data/" "$DATA_PATH"; };
+    rsync -avh --ignore-existing "Resources/config/" "$DATA_PATH" || { sudo rsync -avh --ignore-existing "Resources/config/" "$DATA_PATH"; };
+    chown -R $user "$DATA_PATH" || { sudo chown -R $user "$DATA_PATH"; };
+    chmod -R 774 "$DATA_PATH" || { sudo chmod -R 774 "$DATA_PATH"; };
 }
 
 #-- Checks what you have and what you don't for dependencys that are
@@ -193,8 +201,6 @@ function DependencyCheck() {
             printf "\033[1;33m\nWarning! Automatic package installation is not supported!\n\033[0m";
         ;;
     esac
-
-    mkdir -p ./Project && curl -C - -o ./Project/gdbbin https://nullworks.gitlab.io/cathook/cathook/gdb && chmod +x ./Project/gdbbin || true
 }
 
 function Update() {
@@ -210,9 +216,9 @@ function Update() {
     InstallData;
 
     BUFF=$(grep -c ^'processor' /proc/cpuinfo);
-    pushd "Project/Build" && cmake ../ && cmake --build . --target cathook -- -j$BUFF; popd;
+    pushd "Project/Build" && cmake ../ && cmake --build . --target cunthook -- -j$BUFF; popd;
 
-    echo -e "\nInstalling NavMeshes (may require sudo) ...";
+    echo -e "\nInstalling NavMeshes (may require sudo)...";
     sudo cp -R Resources/meshes/* ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps;
     sudo chmod 755 -R ~/.steam/steam/steamapps/common/Team\ Fortress\ 2/tf/maps;
 }
